config/routes.rb
Xeroizerdemo::Application.routes.draw do

  resources :contacts do
  collection do
    get 'synchronize'
  end
end

get "xero_session/new"
get "xero_session/create"
get "xero_session/destroy"
get "home/index"

root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validate :name, :presence => true
  validate :first_name, :presence => true

  validate :last_name, :presence => true

  validate :email_address, :presence => true, :uniqueness => true


  def self.synchronize(xero_client)
    contacts = xero_client.Contact.all(:order => 'Name')
    emails_list = []
    contacts.entries.each do |contact|
      #try to find by guid
      local_contact = Contact.find_by_xero_uid(contact.contact_id)
      if !local_contact
        #try to find by email
        local_contact = Contact.find_by_email_address(contact.email_address)
        if !local_contact
          #create a new one
          Contact.create!(:name => contact.name, :first_name => contact.first_name, :last_name => contact.last_name, :xero_uid => contact.contact_id, :email_address => contact.email_address)
        end
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  def get_xero_client
    $xero_client = Xeroizer::PublicApplication.new(APP_CONFIG['OAUTH_CONSUMER_KEY'],APP_CONFIG['OAUTH_CONSUMER_SECRET'])

    # Add AccessToken if authorised previously.
    if session[:xero_auth]
      $xero_client.authorize_from_access(
          session[:xero_auth][:access_token],
          session[:xero_auth][:access_key] )
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    if session[:xero_auth] && $xero_client
      begin
        @remote_contacts = $xero_client.Contact.all(:order => 'Name')
      rescue
        #expired session
        session[:xero_auth] = nil
        $xero_client = nil
      end
    else
      @remote_contacts = []
    end
  end

  # GET /contacts
  # GET /contacts.json
  def synchronize
    if session[:xero_auth] && $xero_client
      Contact.synchronize($xero_client)
    else
      raise 'Not connection Found'
    end
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        if session[:xero_auth] && $xero_client
          contact = $xero_client.Contact.build(:name => @contact.name)
          contact.first_name = @contact.first_name
          contact.last_name = @contact.last_name
          contact.last_name = @contact.last_name
          contact.email_address = @contact.email_address
          #contact.add_address(:type => 'STREET', :line1 => '12 Testing Lane', :city => 'Brisbane')
          #contact.add_phone(:type => 'DEFAULT', :area_code => '07', :number => '3033 1234')
          #contact.add_phone(:type => 'MOBILE', :number => '0412 123 456')
          contact.save
        end
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :first_name, :last_name, :email_address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if session[:xero_auth] && $xero_client
      begin
        @contacts = $xero_client.Contact.all(:order => 'Name')
      rescue
        #expired session
        session[:xero_auth] = nil
        $xero_client = nil
      end
    else
      @contacts = []
    end

    #eg. update contact
    #contact = $xero_client.Contact.find("8644bfcd-17ed-47f7-a852-a5fce2d64cdb")
    #contact.name = "Another Name Change"
    #contact.save

  end
end

app/controllers/xero_session_controller.rb
class XeroSessionController < ApplicationController
  before_filter :get_xero_client

  def new
    request_token = $xero_client.request_token(:oauth_callback => 'http://localhost:3000/xero_session/create')
    session[:request_token] = request_token.token
    session[:request_secret] = request_token.secret
    redirect_to request_token.authorize_url
  end

  def create
    $xero_client.authorize_from_request(
        session[:request_token],
        session[:request_secret],
        :oauth_verifier => params[:oauth_verifier] )

    session[:xero_auth] = {
        :access_token => $xero_client.access_token.token,
        :access_key => $xero_client.access_token.secret }

    session.delete(:request_token)
    session.delete(:request_secret)
    redirect_to root_path
  end

  def destroy
    session.delete(:xero_auth)
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/xero_session_helper.rb
module XeroSessionHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing Remote contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>GUID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @remote_contacts.entries.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email_address %></td>
        <td><%# %></td>
        <td><%# link_to 'Show', contact %></td>
        <td><%# link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%# link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Listing local contacts</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email address</th>
    <th>GUID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @contacts.entries.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email_address %></td>
        <td><%= contact.xero_uid %></td>
        <td><%# link_to 'Show', contact %></td>
        <td><%# link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%# link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
<%= link_to 'Synchronize', synchronize_contacts_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @contact.email_address %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h2>Listing of your remote Xero's contacts</h2>

<%if !session[:xero_auth] %>
    <p>Your are not connect with your Xero's account</p>
    <p><%= link_to 'Login with my Xero account', xero_session_new_path %></p>
<%else%>

    <table>
      <thead>
      <tr>
        <th>Remote id</th>
        <th>Name</th>
        <th>Email address</th>
      </tr>
      </thead>

      <tbody>
      <% @contacts.entries.each do |contact| %>
          <tr>
            <td><%= contact.id %></td>
            <td><%= contact.name %></td>
            <td><%= contact.email_address%></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <p><%= link_to 'Log out', xero_session_destroy_path %></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xeroizerdemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/xero_session/create.html.erb
<h1>XeroSession#create</h1>
<p>Find me in app/views/xero_session/create.html.erb</p>

app/views/xero_session/new.html.erb
<h1>XeroSession#new</h1>
<p>Find me in app/views/xero_session/new.html.erb</p>